[project]
name = 'starnote'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sip010-ft-trait]
path = 'contracts/sip010-ft-trait.clar'
clarity_version = 3
epoch = 3.1
[contracts.chinese-coin]
path = 'contracts/chinese-coin.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
